### ISSUE TITLE
Backports from Bitcoin

### ISSUE THREAD

**Issue by CharesFang** [bitcoin-sv/bitcoin-sv#238]
We recently investigated the Bitcoin issues which are related to privacy protection, vulnerability patches, or security enhancements. We have also checked the `repoName` source code. Results show that these issues and their PRs are not backported yet. Henceforth, we suggest that `repoName` should backport the PRs listed below for the considerations of software security and integrity. 

- [ ] Bitcoin [PR#17906](https://github.com/bitcoin/bitcoin/pull/17906), avoid uninitialized reads.
- [ ] Bitcoin [PR#16572](https://github.com/bitcoin/bitcoin/pull/16572), fix a `Char` variable used as `Bool`.
- [ ] Bitcoin [PR#15039](https://github.com/bitcoin/bitcoin/pull/15039), avoid leaking `nLockTime` fingerprint.
- [ ] Bitcoin [PR#14993](https://github.com/bitcoin/bitcoin/pull/14993), fix data race in `InterruptRPC()`.
- [ ] Bitcoin [PR#13907](https://github.com/bitcoin/bitcoin/pull/13907), introduce a maximum size for locators.
- [ ] Bitcoin [PR#13808](https://github.com/bitcoin/bitcoin/pull/13808), shuffle coins before grouping, for privacy protection.
- [ ] Bitcoin [PR#13683](https://github.com/bitcoin/bitcoin/pull/13683), avoid potential null pointer dereference.

Some of these issues and PRs are not severe security-related, but backports can avoid the chaos ecosystem of Bitcoin-forked projects and the potential vulnerabilities in the future. 

Reported by `de957ad9679f28a38f02f00cc7928bce8fb424882ff060a3c09c32895b1474cc`.

**Comment by CharesFang** [comment]
- [ ] Bitcoin [PR#14341](https://github.com/bitcoin/bitcoin/issues/14341) should also be backported from my view. Though I didn't see the completely same functions in Bitcoin-SV (function declaration and its implementations may be different), the way of Bitcoin to handle abnormal Node crash should be referenced.

**Comment by CassClark** [comment]
Internal ticket raised: SVN-1815

**Comment by CassClark** [comment]
@CharesFang 

Following your report of the above issue, the development team are aware of the situation and will assess the risk and take relevant action.

Thanks for taking the time to provide feedback - it's much appreciated.
